-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-09-09 13:44:17 IST
--   site:      SQL Server 2012
--   type:      SQL Server 2012



CREATE TABLE BOOKING 
    (
     BookingID INTEGER NOT NULL , 
     MemberID INTEGER NOT NULL , 
     FacilityID INTEGER NOT NULL , 
     BookingDate DATE NOT NULL , 
     StartTime TIME NOT NULL , 
     EndTime TIME NOT NULL , 
     BookingStatus VARCHAR (20) NOT NULL , 
     MEMBER_MemberID INTEGER NOT NULL , 
     FACILITY_FacilityID INTEGER NOT NULL , 
     PAYMENT_PaymentID INTEGER NOT NULL 
    )
GO 

    


CREATE UNIQUE NONCLUSTERED INDEX 
    BOOKING__IDX ON BOOKING 
    ( 
     PAYMENT_PaymentID 
    ) 
GO

ALTER TABLE BOOKING ADD CONSTRAINT BOOKING_PK PRIMARY KEY CLUSTERED (BookingID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE FACILITY 
    (
     FacilityID INTEGER NOT NULL , 
     FacilityName VARCHAR (100) NOT NULL , 
     FacilityType VARCHAR (50) NOT NULL , 
     Location VARCHAR (150) NOT NULL , 
     Description VARCHAR (255) , 
     Capacity INTEGER NOT NULL , 
     Status VARCHAR (20) NOT NULL 
    )
GO

ALTER TABLE FACILITY ADD CONSTRAINT FACILITY_PK PRIMARY KEY CLUSTERED (FacilityID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE INQUIRY 
    (
     InquiryID INTEGER NOT NULL , 
     Name VARCHAR (100) NOT NULL , 
     Email VARCHAR (100) NOT NULL , 
     Subject VARCHAR (150) NOT NULL , 
     Message VARCHAR (500) NOT NULL , 
     InquiryDate DATE NOT NULL 
    )
GO

ALTER TABLE INQUIRY ADD CONSTRAINT INQUIRY_PK PRIMARY KEY CLUSTERED (InquiryID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE MEMBER 
    (
     MemberID INTEGER NOT NULL , 
     FullNAme VARCHAR (100) NOT NULL , 
     Email VARCHAR (100) NOT NULL , 
     PasswordHash VARCHAR (255) NOT NULL , 
     Phone VARCHAR (20) NOT NULL , 
     Address VARCHAR (255) NOT NULL 
    )
GO

ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_PK PRIMARY KEY CLUSTERED (MemberID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE MEMBER_SPORT 
    (
     MemberID INTEGER NOT NULL , 
     SportID INTEGER NOT NULL , 
     MEMBER_MemberID INTEGER NOT NULL , 
     SPORT_SportID INTEGER NOT NULL 
    )
GO

ALTER TABLE MEMBER_SPORT ADD CONSTRAINT MEMBER_SPORT_PK PRIMARY KEY CLUSTERED (MemberID, SportID, MEMBER_MemberID, SPORT_SportID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE PAYMENT 
    (
     PaymentID INTEGER NOT NULL , 
     BookingID INTEGER NOT NULL , 
     PaymentDate DATE NOT NULL , 
     Amount DECIMAL (10,2) NOT NULL , 
     PaymentMethod VARCHAR (50) NOT NULL , 
     PaymentStatus VARCHAR (20) NOT NULL , 
     TransactionReference VARCHAR (100) 
    )
GO

ALTER TABLE PAYMENT ADD CONSTRAINT PAYMENT_PK PRIMARY KEY CLUSTERED (PaymentID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE REVIEW 
    (
     ReviewID INTEGER NOT NULL , 
     MemberID INTEGER NOT NULL , 
     FacilityID INTEGER NOT NULL , 
     Rating INTEGER NOT NULL , 
     Comment VARCHAR (500) , 
     ReviewDate DATE NOT NULL , 
     MEMBER_MemberID INTEGER NOT NULL , 
     FACILITY_FacilityID INTEGER NOT NULL 
    )
GO

ALTER TABLE REVIEW ADD CONSTRAINT REVIEW_PK PRIMARY KEY CLUSTERED (ReviewID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE SPORT 
    (
     SportID INTEGER NOT NULL , 
     SportName VARCHAR (100) NOT NULL 
    )
GO

ALTER TABLE SPORT ADD CONSTRAINT SPORT_PK PRIMARY KEY CLUSTERED (SportID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE BOOKING 
    ADD CONSTRAINT BOOKING_FACILITY_FK FOREIGN KEY 
    ( 
     FACILITY_FacilityID
    ) 
    REFERENCES FACILITY 
    ( 
     FacilityID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BOOKING 
    ADD CONSTRAINT BOOKING_MEMBER_FK FOREIGN KEY 
    ( 
     MEMBER_MemberID
    ) 
    REFERENCES MEMBER 
    ( 
     MemberID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BOOKING 
    ADD CONSTRAINT BOOKING_PAYMENT_FK FOREIGN KEY 
    ( 
     PAYMENT_PaymentID
    ) 
    REFERENCES PAYMENT 
    ( 
     PaymentID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE MEMBER_SPORT 
    ADD CONSTRAINT MEMBER_SPORT_MEMBER_FK FOREIGN KEY 
    ( 
     MEMBER_MemberID
    ) 
    REFERENCES MEMBER 
    ( 
     MemberID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE MEMBER_SPORT 
    ADD CONSTRAINT MEMBER_SPORT_SPORT_FK FOREIGN KEY 
    ( 
     SPORT_SportID
    ) 
    REFERENCES SPORT 
    ( 
     SportID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE REVIEW 
    ADD CONSTRAINT REVIEW_FACILITY_FK FOREIGN KEY 
    ( 
     FACILITY_FacilityID
    ) 
    REFERENCES FACILITY 
    ( 
     FacilityID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE REVIEW 
    ADD CONSTRAINT REVIEW_MEMBER_FK FOREIGN KEY 
    ( 
     MEMBER_MemberID
    ) 
    REFERENCES MEMBER 
    ( 
     MemberID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             1
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
